FROM node:18-alpine

WORKDIR /app

# Устанавливаем зависимости
COPY package*.json ./
RUN npm ci

# Копируем исходный код
COPY . .

# Открываем порт
EXPOSE 3005

# Запускаем в режиме разработки
CMD ["npm", "run", "start:dev"]